/**
 * Pulls the latest saved content from Supabase and bakes it into
 * src/data/defaultContent.js — so the repo's built-in fallback always matches
 * what you last saved in /dev.
 *
 * Run after editing in /dev:   npm run sync-content
 * Then commit the change:      git add -A && git commit -m "content sync"
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { createClient } from "@supabase/supabase-js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Load VITE_* vars from .env (Node 22+)
process.loadEnvFile(resolve(root, ".env"));

const url = process.env.VITE_SUPABASE_URL;
const key = process.env.VITE_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!url || !key) {
  console.error("Missing VITE_SUPABASE_URL / key in .env");
  process.exit(1);
}

const sb = createClient(url, key);
const { data, error } = await sb
  .from("portfolio_content")
  .select("data, updated_at")
  .eq("id", "main")
  .maybeSingle();

if (error) {
  console.error("Fetch failed:", error.message);
  process.exit(1);
}
if (!data?.data || Object.keys(data.data).length === 0) {
  console.error("The database has no saved content yet — save something in /dev first.");
  process.exit(1);
}

const target = resolve(root, "src/data/defaultContent.js");
const banner =
  "// Seed content. Used as the fallback whenever Supabase is unreachable or empty,\n" +
  "// and as the starting point the /dev panel edits.\n" +
  `// Auto-generated by \`npm run sync-content\` from Supabase (saved ${data.updated_at}).\n`;

writeFileSync(
  target,
  `${banner}\nconst defaultContent = ${JSON.stringify(data.data, null, 2)};\n\nexport default defaultContent;\n`
);

console.log(`✔ src/data/defaultContent.js updated from Supabase (saved ${data.updated_at})`);
console.log("  Commit it to make this the permanent fallback.");
